baseURL = "https://www.micromdm.io/"
languageCode = "en-us"
title = "MicroMDM Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true


[params]
	author = "Joe Blau"
	description = "MicroMDM documentation."
	copyright = "Released under the MIT license"
	provider = "GitHub"
	repo_url = "https://github.com/micromdm/docs"
	logo = "images/logo.svg"

[params.palette]
	primary = "light-blue"
	accent  = "red"

[params.font]
	text = "Ubuntu"
	code = "Ubuntu Mono"

[[menu.main]]
	name   = "MicroMDM docs"
	url    = ""
	weight = 10

[[menu.main]]
	name   = "API"
	url    = "api"
	weight = 20

[[menu.main]]
	name   = "Bugs"
	url    = "bugs"
	weight = 30

[[menu.main]]
	name   = "Community"
	url    = "community"
	weight = 40

[[menu.main]]
	name   = "Contributing"
	url    = "contributing"
	weight = 50

[[menu.main]]
	name   = "DEP"
	url    = "dep"
	weight = 60

[[menu.main]]
	name   = "Deployment"
	url    = "deployment"
	weight = 70

[[menu.main]]
	name   = "Device Block"
	url    = "device-block"
	weight = 80

[[menu.main]]
	name   = "Distribution"
	url    = "distribution"
	weight = 90

[[menu.main]]
	name   = "Hancock"
	url    = "hancock"
	weight = 100

[[menu.main]]
	name   = "mdmcert"
	url    = "mdmcert"
	weight = 110

[[menu.main]]
	name   = "Quickstart"
	url    = "quickstart"
	weight = 120

[[menu.main]]
	name   = "RFCs"
	url    = "rfcs"
	weight = 130

[[menu.main]]
	name   = "Troubleshooting"
	url    = "troubleshooting"
	weight = 140

[[main.menu]]
	name   = "Using MicroMDM"
	url    = "using-micromdm"
	weight = 150


[blackfriday]
	smartypants = true
	fractions = true
	smartDashes = true
	plainIDAnchors = true